language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
services:
- mysql
before_script:
- mysql --user=root --execute='CREATE DATABASE IF NOT EXISTS test;'
- mysql --user=root --execute='GRANT ALL ON test.* TO test@localhost;'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: tA4yo0nkw/2PlYphhpoXtlIgzLSBdJzPb7uomiZiBtPvnCckUwZPV4T44g+zCStK3mJvnfZcIGAxZkympadIlz05DpEmcA5mRQeKR9FJeRWHjF+I+vQesUluLrqKWCbDSLMgl7MIUjPridTGrgkInn13We2OugQ50ZVWeSQJ7NU=
notifications:
  email: false
  slack:
    secure: ApWU9WGaRjVbX5gb8kswLFYIdVKjHkM6NSE//d7i1VAJFMwnYdEq711tXiY3uVvXy67cEgCUj6Hh7oAUsKuxQUPyHEsDX59D7XE1VMO6w0IEww4BY29j46qECgmvvakf7GfVeL1NhHRJM6LTCZ0LtB7VwwI0C7NsXRPjpxou6vo=
sudo: false
